export const TIMEZONES = [
  { value: 'Pacific/Midway', label: 'Midway Island (UTC-11:00)' },
  { value: 'Pacific/Honolulu', label: 'Hawaii (UTC-10:00)' },
  { value: 'America/Anchorage', label: 'Alaska (UTC-09:00)' },
  { value: 'America/Los_Angeles', label: 'Pacific Time - Los Angeles (UTC-08:00)' },
  { value: 'America/Vancouver', label: 'Pacific Time - Vancouver (UTC-08:00)' },
  { value: 'America/Tijuana', label: 'Pacific Time - Tijuana (UTC-08:00)' },
  { value: 'America/Denver', label: 'Mountain Time - Denver (UTC-07:00)' },
  { value: 'America/Phoenix', label: 'Mountain Time - Phoenix (UTC-07:00)' },
  { value: 'America/Chihuahua', label: 'Mountain Time - Chihuahua (UTC-07:00)' },
  { value: 'America/Chicago', label: 'Central Time - Chicago (UTC-06:00)' },
  { value: 'America/Mexico_City', label: 'Central Time - Mexico City (UTC-06:00)' },
  { value: 'America/Guatemala', label: 'Central Time - Guatemala (UTC-06:00)' },
  { value: 'America/New_York', label: 'Eastern Time - New York (UTC-05:00)' },
  { value: 'America/Toronto', label: 'Eastern Time - Toronto (UTC-05:00)' },
  { value: 'America/Bogota', label: 'Colombia Time - Bogota (UTC-05:00)' },
  { value: 'America/Lima', label: 'Peru Time - Lima (UTC-05:00)' },
  { value: 'America/Caracas', label: 'Venezuela Time - Caracas (UTC-04:00)' },
  { value: 'America/Santiago', label: 'Chile Time - Santiago (UTC-04:00)' },
  { value: 'America/Halifax', label: 'Atlantic Time - Halifax (UTC-04:00)' },
  { value: 'America/La_Paz', label: 'Bolivia Time - La Paz (UTC-04:00)' },
  { value: 'America/St_Johns', label: 'Newfoundland Time (UTC-03:30)' },
  { value: 'America/Sao_Paulo', label: 'Brazil Time - São Paulo (UTC-03:00)' },
  { value: 'America/Buenos_Aires', label: 'Argentina Time - Buenos Aires (UTC-03:00)' },
  { value: 'America/Montevideo', label: 'Uruguay Time - Montevideo (UTC-03:00)' },
  { value: 'America/Godthab', label: 'Greenland Time (UTC-03:00)' },
  { value: 'Atlantic/South_Georgia', label: 'South Georgia (UTC-02:00)' },
  { value: 'Atlantic/Azores', label: 'Azores (UTC-01:00)' },
  { value: 'Atlantic/Cape_Verde', label: 'Cape Verde (UTC-01:00)' },
  { value: 'UTC', label: 'UTC (UTC+00:00)' },
  { value: 'Europe/London', label: 'London (UTC+00:00)' },
  { value: 'Europe/Dublin', label: 'Dublin (UTC+00:00)' },
  { value: 'Europe/Lisbon', label: 'Lisbon (UTC+00:00)' },
  { value: 'Africa/Casablanca', label: 'Casablanca (UTC+00:00)' },
  { value: 'Africa/Lagos', label: 'Lagos (UTC+01:00)' },
  { value: 'Europe/Paris', label: 'Paris (UTC+01:00)' },
  { value: 'Europe/Berlin', label: 'Berlin (UTC+01:00)' },
  { value: 'Europe/Rome', label: 'Rome (UTC+01:00)' },
  { value: 'Europe/Madrid', label: 'Madrid (UTC+01:00)' },
  { value: 'Europe/Amsterdam', label: 'Amsterdam (UTC+01:00)' },
  { value: 'Europe/Brussels', label: 'Brussels (UTC+01:00)' },
  { value: 'Europe/Vienna', label: 'Vienna (UTC+01:00)' },
  { value: 'Europe/Warsaw', label: 'Warsaw (UTC+01:00)' },
  { value: 'Europe/Prague', label: 'Prague (UTC+01:00)' },
  { value: 'Europe/Stockholm', label: 'Stockholm (UTC+01:00)' },
  { value: 'Europe/Athens', label: 'Athens (UTC+02:00)' },
  { value: 'Europe/Bucharest', label: 'Bucharest (UTC+02:00)' },
  { value: 'Europe/Helsinki', label: 'Helsinki (UTC+02:00)' },
  { value: 'Europe/Istanbul', label: 'Istanbul (UTC+02:00)' },
  { value: 'Africa/Cairo', label: 'Cairo (UTC+02:00)' },
  { value: 'Africa/Johannesburg', label: 'Johannesburg (UTC+02:00)' },
  { value: 'Asia/Jerusalem', label: 'Jerusalem (UTC+02:00)' },
  { value: 'Asia/Beirut', label: 'Beirut (UTC+02:00)' },
  { value: 'Europe/Moscow', label: 'Moscow (UTC+03:00)' },
  { value: 'Asia/Baghdad', label: 'Baghdad (UTC+03:00)' },
  { value: 'Asia/Kuwait', label: 'Kuwait (UTC+03:00)' },
  { value: 'Asia/Riyadh', label: 'Riyadh (UTC+03:00)' },
  { value: 'Africa/Nairobi', label: 'Nairobi (UTC+03:00)' },
  { value: 'Asia/Tehran', label: 'Tehran (UTC+03:30)' },
  { value: 'Asia/Dubai', label: 'Dubai (UTC+04:00)' },
  { value: 'Asia/Muscat', label: 'Muscat (UTC+04:00)' },
  { value: 'Asia/Baku', label: 'Baku (UTC+04:00)' },
  { value: 'Asia/Tbilisi', label: 'Tbilisi (UTC+04:00)' },
  { value: 'Asia/Yerevan', label: 'Yerevan (UTC+04:00)' },
  { value: 'Asia/Kabul', label: 'Kabul (UTC+04:30)' },
  { value: 'Asia/Karachi', label: 'Karachi (UTC+05:00)' },
  { value: 'Asia/Tashkent', label: 'Tashkent (UTC+05:00)' },
  { value: 'Asia/Kolkata', label: 'India - Kolkata (UTC+05:30)' },
  { value: 'Asia/Mumbai', label: 'India - Mumbai (UTC+05:30)' },
  { value: 'Asia/Delhi', label: 'India - Delhi (UTC+05:30)' },
  { value: 'Asia/Colombo', label: 'Colombo (UTC+05:30)' },
  { value: 'Asia/Kathmandu', label: 'Kathmandu (UTC+05:45)' },
  { value: 'Asia/Dhaka', label: 'Dhaka (UTC+06:00)' },
  { value: 'Asia/Almaty', label: 'Almaty (UTC+06:00)' },
  { value: 'Asia/Yangon', label: 'Yangon (UTC+06:30)' },
  { value: 'Asia/Bangkok', label: 'Bangkok (UTC+07:00)' },
  { value: 'Asia/Jakarta', label: 'Jakarta (UTC+07:00)' },
  { value: 'Asia/Ho_Chi_Minh', label: 'Ho Chi Minh City (UTC+07:00)' },
  { value: 'Asia/Shanghai', label: 'Shanghai (UTC+08:00)' },
  { value: 'Asia/Beijing', label: 'Beijing (UTC+08:00)' },
  { value: 'Asia/Hong_Kong', label: 'Hong Kong (UTC+08:00)' },
  { value: 'Asia/Singapore', label: 'Singapore (UTC+08:00)' },
  { value: 'Asia/Taipei', label: 'Taipei (UTC+08:00)' },
  { value: 'Asia/Manila', label: 'Manila (UTC+08:00)' },
  { value: 'Asia/Kuala_Lumpur', label: 'Kuala Lumpur (UTC+08:00)' },
  { value: 'Australia/Perth', label: 'Perth (UTC+08:00)' },
  { value: 'Asia/Tokyo', label: 'Tokyo (UTC+09:00)' },
  { value: 'Asia/Seoul', label: 'Seoul (UTC+09:00)' },
  { value: 'Asia/Pyongyang', label: 'Pyongyang (UTC+09:00)' },
  { value: 'Australia/Adelaide', label: 'Adelaide (UTC+09:30)' },
  { value: 'Australia/Darwin', label: 'Darwin (UTC+09:30)' },
  { value: 'Australia/Sydney', label: 'Sydney (UTC+10:00)' },
  { value: 'Australia/Melbourne', label: 'Melbourne (UTC+10:00)' },
  { value: 'Australia/Brisbane', label: 'Brisbane (UTC+10:00)' },
  { value: 'Pacific/Guam', label: 'Guam (UTC+10:00)' },
  { value: 'Pacific/Port_Moresby', label: 'Port Moresby (UTC+10:00)' },
  { value: 'Australia/Hobart', label: 'Hobart (UTC+10:00)' },
  { value: 'Pacific/Noumea', label: 'Noumea (UTC+11:00)' },
  { value: 'Pacific/Guadalcanal', label: 'Guadalcanal (UTC+11:00)' },
  { value: 'Pacific/Auckland', label: 'Auckland (UTC+12:00)' },
  { value: 'Pacific/Fiji', label: 'Fiji (UTC+12:00)' },
  { value: 'Pacific/Tongatapu', label: 'Tongatapu (UTC+13:00)' },
  { value: 'Pacific/Apia', label: 'Apia (UTC+13:00)' },
]

export type CityLocation = {
  city: string
  country: string
  timezone: string
  displayName: string
}

export const CITY_LOCATIONS: CityLocation[] = [
  { city: 'New York', country: 'USA', timezone: 'America/New_York', displayName: 'New York, USA' },
  { city: 'Los Angeles', country: 'USA', timezone: 'America/Los_Angeles', displayName: 'Los Angeles, USA' },
  { city: 'Chicago', country: 'USA', timezone: 'America/Chicago', displayName: 'Chicago, USA' },
  { city: 'Houston', country: 'USA', timezone: 'America/Chicago', displayName: 'Houston, USA' },
  { city: 'Phoenix', country: 'USA', timezone: 'America/Phoenix', displayName: 'Phoenix, USA' },
  { city: 'Philadelphia', country: 'USA', timezone: 'America/New_York', displayName: 'Philadelphia, USA' },
  { city: 'San Antonio', country: 'USA', timezone: 'America/Chicago', displayName: 'San Antonio, USA' },
  { city: 'San Diego', country: 'USA', timezone: 'America/Los_Angeles', displayName: 'San Diego, USA' },
  { city: 'Dallas', country: 'USA', timezone: 'America/Chicago', displayName: 'Dallas, USA' },
  { city: 'San Jose', country: 'USA', timezone: 'America/Los_Angeles', displayName: 'San Jose, USA' },
  { city: 'Austin', country: 'USA', timezone: 'America/Chicago', displayName: 'Austin, USA' },
  { city: 'Seattle', country: 'USA', timezone: 'America/Los_Angeles', displayName: 'Seattle, USA' },
  { city: 'Denver', country: 'USA', timezone: 'America/Denver', displayName: 'Denver, USA' },
  { city: 'Boston', country: 'USA', timezone: 'America/New_York', displayName: 'Boston, USA' },
  { city: 'Miami', country: 'USA', timezone: 'America/New_York', displayName: 'Miami, USA' },
  { city: 'Atlanta', country: 'USA', timezone: 'America/New_York', displayName: 'Atlanta, USA' },
  { city: 'Toronto', country: 'Canada', timezone: 'America/Toronto', displayName: 'Toronto, Canada' },
  { city: 'Vancouver', country: 'Canada', timezone: 'America/Vancouver', displayName: 'Vancouver, Canada' },
  { city: 'Montreal', country: 'Canada', timezone: 'America/Toronto', displayName: 'Montreal, Canada' },
  { city: 'Calgary', country: 'Canada', timezone: 'America/Denver', displayName: 'Calgary, Canada' },
  { city: 'Ottawa', country: 'Canada', timezone: 'America/Toronto', displayName: 'Ottawa, Canada' },
  { city: 'London', country: 'UK', timezone: 'Europe/London', displayName: 'London, UK' },
  { city: 'Manchester', country: 'UK', timezone: 'Europe/London', displayName: 'Manchester, UK' },
  { city: 'Birmingham', country: 'UK', timezone: 'Europe/London', displayName: 'Birmingham, UK' },
  { city: 'Edinburgh', country: 'UK', timezone: 'Europe/London', displayName: 'Edinburgh, UK' },
  { city: 'Dublin', country: 'Ireland', timezone: 'Europe/Dublin', displayName: 'Dublin, Ireland' },
  { city: 'Paris', country: 'France', timezone: 'Europe/Paris', displayName: 'Paris, France' },
  { city: 'Lyon', country: 'France', timezone: 'Europe/Paris', displayName: 'Lyon, France' },
  { city: 'Marseille', country: 'France', timezone: 'Europe/Paris', displayName: 'Marseille, France' },
  { city: 'Berlin', country: 'Germany', timezone: 'Europe/Berlin', displayName: 'Berlin, Germany' },
  { city: 'Munich', country: 'Germany', timezone: 'Europe/Berlin', displayName: 'Munich, Germany' },
  { city: 'Hamburg', country: 'Germany', timezone: 'Europe/Berlin', displayName: 'Hamburg, Germany' },
  { city: 'Frankfurt', country: 'Germany', timezone: 'Europe/Berlin', displayName: 'Frankfurt, Germany' },
  { city: 'Madrid', country: 'Spain', timezone: 'Europe/Madrid', displayName: 'Madrid, Spain' },
  { city: 'Barcelona', country: 'Spain', timezone: 'Europe/Madrid', displayName: 'Barcelona, Spain' },
  { city: 'Rome', country: 'Italy', timezone: 'Europe/Rome', displayName: 'Rome, Italy' },
  { city: 'Milan', country: 'Italy', timezone: 'Europe/Rome', displayName: 'Milan, Italy' },
  { city: 'Amsterdam', country: 'Netherlands', timezone: 'Europe/Amsterdam', displayName: 'Amsterdam, Netherlands' },
  { city: 'Brussels', country: 'Belgium', timezone: 'Europe/Brussels', displayName: 'Brussels, Belgium' },
  { city: 'Vienna', country: 'Austria', timezone: 'Europe/Vienna', displayName: 'Vienna, Austria' },
  { city: 'Warsaw', country: 'Poland', timezone: 'Europe/Warsaw', displayName: 'Warsaw, Poland' },
  { city: 'Prague', country: 'Czech Republic', timezone: 'Europe/Prague', displayName: 'Prague, Czech Republic' },
  { city: 'Stockholm', country: 'Sweden', timezone: 'Europe/Stockholm', displayName: 'Stockholm, Sweden' },
  { city: 'Athens', country: 'Greece', timezone: 'Europe/Athens', displayName: 'Athens, Greece' },
  { city: 'Bucharest', country: 'Romania', timezone: 'Europe/Bucharest', displayName: 'Bucharest, Romania' },
  { city: 'Helsinki', country: 'Finland', timezone: 'Europe/Helsinki', displayName: 'Helsinki, Finland' },
  { city: 'Istanbul', country: 'Turkey', timezone: 'Europe/Istanbul', displayName: 'Istanbul, Turkey' },
  { city: 'Moscow', country: 'Russia', timezone: 'Europe/Moscow', displayName: 'Moscow, Russia' },
  { city: 'Dubai', country: 'UAE', timezone: 'Asia/Dubai', displayName: 'Dubai, UAE' },
  { city: 'Abu Dhabi', country: 'UAE', timezone: 'Asia/Dubai', displayName: 'Abu Dhabi, UAE' },
  { city: 'Riyadh', country: 'Saudi Arabia', timezone: 'Asia/Riyadh', displayName: 'Riyadh, Saudi Arabia' },
  { city: 'Cairo', country: 'Egypt', timezone: 'Africa/Cairo', displayName: 'Cairo, Egypt' },
  { city: 'Johannesburg', country: 'South Africa', timezone: 'Africa/Johannesburg', displayName: 'Johannesburg, South Africa' },
  { city: 'Cape Town', country: 'South Africa', timezone: 'Africa/Johannesburg', displayName: 'Cape Town, South Africa' },
  { city: 'Lagos', country: 'Nigeria', timezone: 'Africa/Lagos', displayName: 'Lagos, Nigeria' },
  { city: 'Nairobi', country: 'Kenya', timezone: 'Africa/Nairobi', displayName: 'Nairobi, Kenya' },
  { city: 'Mumbai', country: 'India', timezone: 'Asia/Kolkata', displayName: 'Mumbai, India' },
  { city: 'Delhi', country: 'India', timezone: 'Asia/Kolkata', displayName: 'Delhi, India' },
  { city: 'Bangalore', country: 'India', timezone: 'Asia/Kolkata', displayName: 'Bangalore, India' },
  { city: 'Hyderabad', country: 'India', timezone: 'Asia/Kolkata', displayName: 'Hyderabad, India' },
  { city: 'Chennai', country: 'India', timezone: 'Asia/Kolkata', displayName: 'Chennai, India' },
  { city: 'Kolkata', country: 'India', timezone: 'Asia/Kolkata', displayName: 'Kolkata, India' },
  { city: 'Pune', country: 'India', timezone: 'Asia/Kolkata', displayName: 'Pune, India' },
  { city: 'Karachi', country: 'Pakistan', timezone: 'Asia/Karachi', displayName: 'Karachi, Pakistan' },
  { city: 'Dhaka', country: 'Bangladesh', timezone: 'Asia/Dhaka', displayName: 'Dhaka, Bangladesh' },
  { city: 'Bangkok', country: 'Thailand', timezone: 'Asia/Bangkok', displayName: 'Bangkok, Thailand' },
  { city: 'Singapore', country: 'Singapore', timezone: 'Asia/Singapore', displayName: 'Singapore' },
  { city: 'Kuala Lumpur', country: 'Malaysia', timezone: 'Asia/Kuala_Lumpur', displayName: 'Kuala Lumpur, Malaysia' },
  { city: 'Jakarta', country: 'Indonesia', timezone: 'Asia/Jakarta', displayName: 'Jakarta, Indonesia' },
  { city: 'Manila', country: 'Philippines', timezone: 'Asia/Manila', displayName: 'Manila, Philippines' },
  { city: 'Ho Chi Minh City', country: 'Vietnam', timezone: 'Asia/Ho_Chi_Minh', displayName: 'Ho Chi Minh City, Vietnam' },
  { city: 'Beijing', country: 'China', timezone: 'Asia/Shanghai', displayName: 'Beijing, China' },
  { city: 'Shanghai', country: 'China', timezone: 'Asia/Shanghai', displayName: 'Shanghai, China' },
  { city: 'Hong Kong', country: 'Hong Kong', timezone: 'Asia/Hong_Kong', displayName: 'Hong Kong' },
  { city: 'Taipei', country: 'Taiwan', timezone: 'Asia/Taipei', displayName: 'Taipei, Taiwan' },
  { city: 'Tokyo', country: 'Japan', timezone: 'Asia/Tokyo', displayName: 'Tokyo, Japan' },
  { city: 'Osaka', country: 'Japan', timezone: 'Asia/Tokyo', displayName: 'Osaka, Japan' },
  { city: 'Seoul', country: 'South Korea', timezone: 'Asia/Seoul', displayName: 'Seoul, South Korea' },
  { city: 'Sydney', country: 'Australia', timezone: 'Australia/Sydney', displayName: 'Sydney, Australia' },
  { city: 'Melbourne', country: 'Australia', timezone: 'Australia/Melbourne', displayName: 'Melbourne, Australia' },
  { city: 'Brisbane', country: 'Australia', timezone: 'Australia/Brisbane', displayName: 'Brisbane, Australia' },
  { city: 'Perth', country: 'Australia', timezone: 'Australia/Perth', displayName: 'Perth, Australia' },
  { city: 'Adelaide', country: 'Australia', timezone: 'Australia/Adelaide', displayName: 'Adelaide, Australia' },
  { city: 'Auckland', country: 'New Zealand', timezone: 'Pacific/Auckland', displayName: 'Auckland, New Zealand' },
  { city: 'Wellington', country: 'New Zealand', timezone: 'Pacific/Auckland', displayName: 'Wellington, New Zealand' },
  { city: 'Mexico City', country: 'Mexico', timezone: 'America/Mexico_City', displayName: 'Mexico City, Mexico' },
  { city: 'Guadalajara', country: 'Mexico', timezone: 'America/Mexico_City', displayName: 'Guadalajara, Mexico' },
  { city: 'São Paulo', country: 'Brazil', timezone: 'America/Sao_Paulo', displayName: 'São Paulo, Brazil' },
  { city: 'Rio de Janeiro', country: 'Brazil', timezone: 'America/Sao_Paulo', displayName: 'Rio de Janeiro, Brazil' },
  { city: 'Buenos Aires', country: 'Argentina', timezone: 'America/Buenos_Aires', displayName: 'Buenos Aires, Argentina' },
  { city: 'Santiago', country: 'Chile', timezone: 'America/Santiago', displayName: 'Santiago, Chile' },
  { city: 'Lima', country: 'Peru', timezone: 'America/Lima', displayName: 'Lima, Peru' },
  { city: 'Bogota', country: 'Colombia', timezone: 'America/Bogota', displayName: 'Bogota, Colombia' },
  { city: 'Caracas', country: 'Venezuela', timezone: 'America/Caracas', displayName: 'Caracas, Venezuela' },
]
